version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies

  - package-ecosystem: "pip"
    directory: "/hardwaremon_app/backend_fastapi"
    schedule:
      interval: "weekly"
    labels:
      - dependencies

  - package-ecosystem: "pub"
    directory: "/hardwaremon_app"
    schedule:
      interval: "weekly"
    labels:
      - dependencies

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
