name: Build Flatpak

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            flatpak \
            flatpak-builder \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            python3-pip \
            python3-venv

      - name: Install Flatpak runtimes
        run: |
          flatpak remote-add --user --if-not-exists flathub \
            https://flathub.org/repo/flathub.flatpakrepo

          flatpak install --user -y \
            flathub org.freedesktop.Platform//24.08

          flatpak install --user -y \
            flathub org.freedesktop.Sdk//24.08

      - name: Flutter pub get
        working-directory: flutter_gui
        run: flutter pub get

      - name: Build Flutter Linux app
        working-directory: flutter_gui
        run: flutter build linux --release

      - name: Install backend dependencies
        working-directory: flutter_gui/backend_fastapi
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build backend executable
        working-directory: flutter_gui/backend_fastapi
        run: |
          pyinstaller backend.spec

      - name: Copy backend into bundle
        run: |
          mkdir -p flutter_gui/build/linux/x64/release/bundle/backend

          cp -a \
            flutter_gui/backend_fastapi/dist/backend/. \
            flutter_gui/build/linux/x64/release/bundle/backend/

          chmod +x \
            flutter_gui/build/linux/x64/release/bundle/backend/backend

      - name: Build Flatpak
        run: |
          flatpak-builder build-dir \
            flatpak/com.hardwaremon.HardwareMon.yml \
            --force-clean

      - name: Export Flatpak repository
        run: |
          flatpak build-export repo build-dir

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle \
            repo \
            hardwaremon.flatpak \
            com.hardwaremon.HardwareMon

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: hardwaremon-flatpak
          path: hardwaremon.flatpak

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: hardwaremon.flatpak
