name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - uses: pascalgn/size-label-action@v0.5.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
